apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-registry
    app.kubernetes.io/part-of: release-registry
  name: release-registry
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-registry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: release-registry
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8078
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
